# bun workspace configuration
[install]
# Registry configuration
registry = "https://registry.npmjs.org"

# Security configuration
trusted-dependencies = [
  "@tailwindcss/oxide",
  "core-js", 
  "esbuild",
  "onnxruntime-node",
  "oxc-resolver", 
  "protobufjs",
  "sharp",
  "wasm-pack"
]

[install.scopes]
# Scope configuration can go here if needed