[package]
name = "moq-lite"
description = "Media over QUIC - Transport (Lite)"
authors = ["Luke Curley"]
repository = "https://github.com/kixelated/moq-rs"
license = "MIT OR Apache-2.0"

version = "0.1.0"
edition = "2021"

keywords = ["quic", "http3", "webtransport", "media", "live"]
categories = ["multimedia", "network-programming", "web-programming"]

[dependencies]
bytes = "1"
thiserror = "2"
tracing = "0.1"

tokio = { workspace = true, features = [
	"macros",
	"io-util",
	"sync",
	"test-util",
] }

web-transport = { workspace = true }
futures = "0.3"
num_enum = "0.7"
web-async = "0.1"
