[workspace]
members = ["moq-transfork", "moq-relay", "moq-clock", "moq-native", "moq-karp"]
resolver = "2"

[workspace.dependencies]
# Make it easy to test web-transport changes
#web-transport = { path = "../web-transport-rs/web-transport" }
web-transport = "0.6"

# Use debug symbols in production until things are more stable
[profile.release]
debug = true
