[workspace]
members = [
	"moq/lite",
	"moq/clock",
	"moq/relay",
	"moq/native",
	"hang/lib",
	"hang/cli",
	"hang/wasm",
]
resolver = "2"

[workspace.dependencies]
# Make it easy to test web-transport changes
#web-transport = { path = "../web-transport-rs/web-transport" }
web-transport = "0.8"

moq-lite = { path = "moq/lite" }
moq-native = { path = "moq/native" }
hang = { path = "hang/lib" }

tokio = "1.43"

[profile.release.package.moq-wasm]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
