[workspace]
members = ["moq-transfork", "moq-relay", "moq-clock", "moq-native", "moq-karp"]
# These are separate while they have annoying dependencies.
# 	moq-web: requires wasm target
# 	moq-gst: requires gstreamer is installed
exclude = ["moq-web", "moq-gst"]
resolver = "2"

[workspace.dependencies]
# Make it easy to test web-transport changes
#web-transport = { path = "../web-transport-rs/web-transport" }
web-transport = "0.6.2"

# Use debug symbols in production until things are more stable
[profile.release]
debug = true
