x-moq: &x-moq
  volumes:
    - ./dev/localhost.crt:/etc/tls/cert:ro
    - ./dev/localhost.key:/etc/tls/key:ro
    - certs:/etc/ssl/certs
  depends_on:
    install-certs:
      condition: service_completed_successfully

services:
  relay1:
    <<: *x-moq
    build:
      context: .
      dockerfile: Dockerfile
      target: moq-relay
    command: --tls-cert /etc/tls/cert --tls-key /etc/tls/key --tls-disable-verify --cluster-node relay1 --cluster-root relay1 --dev
    ports:
      - "4443:443"
      - "4443:443/udp"

  relay2:
    <<: *x-moq
    build:
      context: .
      dockerfile: Dockerfile
      target: moq-relay
    command: --tls-cert /etc/tls/cert --tls-key /etc/tls/key --tls-disable-verify --cluster-node relay2 --cluster-root relay1 --dev
    depends_on:
      - relay1
    ports:
      - "4444:443"
      - "4444:443/udp"

  pub:
    <<: *x-moq
    build:
      context: .
      dockerfile: Dockerfile
      target: moq-bbb
    # Change to relay1 if you don't want to test clustering
    command: --tls-disable-verify --path bbb --url https://relay2
    depends_on:
      - relay2

  clock:
    <<: *x-moq
    build:
      context: .
      dockerfile: Dockerfile
      target: moq-clock
    command: --tls-disable-verify --publish https://relay1
    depends_on:
      - relay1

  install-certs:
    image: golang:latest
    working_dir: /work
    command: go run filippo.io/mkcert -install
    environment:
      CAROOT: /work/caroot
    volumes:
      - ${CAROOT:-.}:/work/caroot
      - certs:/etc/ssl/certs
      - ./dev/go.mod:/work/go.mod:ro
      - ./dev/go.sum:/work/go.sum:ro

volumes:
  certs:
