[log]
# Enable debug logging for development.
# The RUST_LOG environment variable will take precedence.
level = "debug"

[server]
# Listen for QUIC connections on UDP:4443
# Sometimes IPv6 causes issues; try 127.0.0.1:4443 instead.
bind = "[::]:4443"

# Generate a self-signed certificate for the server.
# This is used for local development
tls_generate = ["localhost"]

[cluster]
# Include our hostname so leaf nodes can connect to us.
node = "localhost:4443"

# Authentication is rather crude because it's GOOD ENOUGH for now.
# The first part of the path is used to determine the key to use.
# ex. `/demo/XXXXX` will use the "demo" key.
#
# - If an empty string is specified, then no authentication is required.
# - If there is no key specified in this configuration file, then the connection is rejected.
# - If there is an authentication key specified, then the rest of the path is used as the authentication token.
#
# == Example ==
# Let's say we have a JWK file `secret.jwk` output from the moq-token CLI.
# We first need to configure it:
#
# ```toml
#   [auth.key]
#   secret = "secret.jwk"
# ```
#
# The moq-token CLI can sign tokens for us with parameters like:
# ```sh
#   moq-token sign --key secret.jwk --subscribe "" --publish "foo/"
# ```
#
# This will output a base64 JSON token that we can append to the path: `/secret/XXXXX`
# NOTE: The key can be used for any path (or multiple), as it's not scoped to "secret".
#
# This specific token will allow subscribing to `/secret/**` and publishing to `/secret/foo/**`.
[auth.key]
# All that explanation just to disable authentication for the demo/ path.
demo = ""
