# A simple configuration for a local relay server.
# This is used for local development and has authentication disabled.

[log]
# Enable debug logging for development.
# The RUST_LOG environment variable will take precedence.
level = "debug"

[server]
# Listen for QUIC connections on UDP:4443
# Sometimes IPv6 causes issues; try 127.0.0.1:4443 instead.
listen = "[::]:4443"

# Generate a self-signed certificate for the given hostnames.
# This is used for local development, in conjunction with a fingerprint, or with TLS verification disabled.
tls.generate = ["localhost"]

[web.http]
# Listen for HTTP and WebSocket connections on the given TCP address.
# This is unfortunately required to serve certificate.sha256 for local development.
# However, as a bonus, we can serve tracks via both HTTP and WebSocket fallbacks.
listen = "[::]:4443"

# See root.toml and leaf.toml for auth and clustering examples.
[auth]
# Allow anonymous access to everything.
public = ""
