name: Check

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      # Cache Rust dependencies and build artifacts
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rs -> target"
          cache-on-failure: true

      # Run checks with cached dependencies
      - run: nix develop --command just check --workspace
