name: Docker

on:
  push:
    tags:
      - 'moq-relay-v*'
      - 'moq-clock-v*'
      # NOTE: The -cli is automatically removed
      - 'hang-cli-v*'

env:
  REGISTRY: docker.io/kixelated

jobs:
  deploy:
    name: Release

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Figure out the docker image based on the tag
      - id: parse
        run: |
          ref=${GITHUB_REF#refs/tags/}
          if [[ "$ref" =~ ^([a-z-]+)-v([0-9.]+)$ ]]; then
            full_target="${BASH_REMATCH[1]}"
            version="${BASH_REMATCH[2]}"
            # Strip "-cli" suffix from target if present
            target="${full_target%-cli}"
            echo "target=$target" >> $GITHUB_OUTPUT
            echo "version=$version" >> $GITHUB_OUTPUT
          else
            echo "Tag format not recognized." >&2
            exit 1
          fi

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Enable flakes
        run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf

      # Login to docker.io
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push multiplatform images using Just
      - name: Build and push multi-platform Docker images
        run: cd rs && nix develop --command just docker-release ${{ steps.parse.outputs.target }} ${{ env.REGISTRY }} ${{ steps.parse.outputs.version }}
