name: Docker

on:
  push:
    tags:
      - 'moq-relay-v*'
      - 'moq-clock-v*'
      # NOTE: The -cli is automatically removed
      - 'hang-cli-v*'

env:
  REGISTRY: docker.io/kixelated

jobs:
  deploy:
    name: Release

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Figure out the docker image based on the tag
      - id: parse
        run: |
          ref=${GITHUB_REF#refs/tags/}
          if [[ "$ref" =~ ^([a-z-]+)(?:-cli)?-v([0-9.]+)$ ]]; then
            target=${BASH_REMATCH[1]}
            version=${BASH_REMATCH[2]}
            echo "target=$target" >> $GITHUB_OUTPUT
            echo "version=$version" >> $GITHUB_OUTPUT
          else
            echo "Tag format not recognized." >&2
            exit 1
          fi

      # I'm paying for Depot for faster ARM builds.
      - uses: depot/setup-action@v1

      # Login to docker.io
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image with Depot
      - uses: depot/build-push-action@v1
        with:
          project: r257ctfqm6
          file: rs/Dockerfile
          context: rs
          push: true
          target: ${{ steps.parse.outputs.target }}
          tags: |
            ${{ env.REGISTRY }}/${{ steps.parse.outputs.target }}:${{ steps.parse.outputs.version }}
            ${{ env.REGISTRY }}/${{ steps.parse.outputs.target }}:latest
          platforms: linux/amd64,linux/arm64
