name: Javascript

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Use depot/docker to run CI so it's semi-cached.
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          project: r257ctfqm6
          file: js/Dockerfile
          context: js