name: Javascript

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Enable flakes
        run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf

      - name: Set up pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('js/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Check
        run: cd js && nix develop --command just check