name: Javascript

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./js

    steps:
      - uses: actions/checkout@v4

      # Install Just to run CI scripts
      - uses: extractions/setup-just@v3

      # Install pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      # Install Node
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      # Make sure u guys don't write bad code
      - run: just check
      - run: just test
