name: Rust

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
      - run: nix develop --command just check
