name: Rust

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Enable flakes
        run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf

      - name: Set up a Rust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            rs/target/
          key: rust-${{ runner.os }}-${{ hashFiles('rs/Cargo.lock') }}
          restore-keys: |
            rust-${{ runner.os }}-

      - name: Check
        run: cd rs && nix develop --command just check --workspace