name: Rust

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Use depot/docker to build the binaries and run CI.
      - name: Build dependencies
        uses: depot/build-push-action@v1
        with:
          project: r257ctfqm6
          file: rs/Dockerfile
          context: rs