name: Rust

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Use depot/docker to build the binaries and run CI.
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          project: r257ctfqm6
          file: rs/Dockerfile
          context: rs