name: Rust

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./rs

    steps:
      - uses: actions/checkout@v4

      # Install Rust with clippy/rustfmt
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          target: wasm32-unknown-unknown

      # Install Just to run CI scripts
      - uses: extractions/setup-just@v3

      # Cargo binstall is used to install tools faster than compiling them from source.
      - uses: cargo-bins/cargo-binstall@main
      - run: just setup-tools

      # Required for unstable WebCodecs and WebTransport
      - run: echo "RUSTFLAGS=--cfg=web_sys_unstable_apis" >> $GITHUB_ENV

      # Unfortunately we need gstreamer to fully check everything
      - name: Setup GStreamer
        run: |
          sudo apt-get update
          sudo apt-get remove libunwind-*
          sudo apt-get install -y \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-bad1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            gstreamer1.0-tools \
            gstreamer1.0-x \
            gstreamer1.0-alsa \
            gstreamer1.0-gl \
            gstreamer1.0-gtk3 \
            gstreamer1.0-qt5 \
            gstreamer1.0-pulseaudio

      # Make sure u guys don't write bad code
      - run: just check --workspace
      - run: just test --workspace
